version: "1.0"
info:
  model: int-scaffold
packages:
- name: IBM_DEMOProject
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitBranch: main
services:
- serviceName: project.ibm_demo.integrations:test
  packages:
  - name: IBM_DEMOProject
    version: "1.0"
  - name: JcDangerousPackage
    version: "1.0"
- serviceName: jc.dangerous:suspiciousService
  packages:
  - name: JcDangerousPackage
    version: "1.0"
- serviceName: pub.utils:executeOSCommand
  packages:
  - name: WmPublic
    version: 11.1.0.0.1969
